USE [BlueHr]
GO

/****** Object:  Index [PK_RewardsAndPenalty]    Script Date: 12/06/2016 14:59:17 ******/
ALTER TABLE [dbo].[RewardsAndPenalty] ADD  CONSTRAINT [PK_RewardsAndPenalty] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [BlueHr]
GO

/****** Object:  Index [PK_Recruit]    Script Date: 12/06/2016 14:59:02 ******/
ALTER TABLE [dbo].[Recruit] ADD  CONSTRAINT [PK_Recruit] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


