USE [BlueHr]
GO

/****** Object:  Table [dbo].[WorkAndRest]    Script Date: 09/20/2016 03:26:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[WorkAndRest](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[dateAt] [datetime] NULL,
	[dateType] [int] NULL,
	[remark] [varchar](255) NULL,
 CONSTRAINT [PK_WorkAndRest] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


